"""add profile_data to users

Revision ID: ab62d9faf4cb
Revises: cce39f9d6c5b
Create Date: 2026-01-16 21:14:44.696900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab62d9faf4cb'
down_revision: Union[str, Sequence[str], None] = 'cce39f9d6c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_data')
    # ### end Alembic commands ###
