"""create games table

Revision ID: fffff66d5729
Revises: ab62d9faf4cb
Create Date: 2026-01-16 21:56:29.647580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffff66d5729'
down_revision: Union[str, Sequence[str], None] = 'ab62d9faf4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('perf_type', sa.String(length=50), nullable=False),
    sa.Column('time_control', sa.String(length=50), nullable=False),
    sa.Column('opponent_name', sa.String(length=255), nullable=False),
    sa.Column('opponent_rating', sa.Integer(), nullable=True),
    sa.Column('user_color', sa.String(length=10), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('termination', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_games_user_created', 'games', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_games_user_perf', 'games', ['user_id', 'perf_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_games_user_perf', table_name='games')
    op.drop_index('idx_games_user_created', table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
